### ISSUE TITLE
Npm 7 peerDependency issue

### ISSUE THREAD

**Issue by neneodonkor** [preactjs/next-plugin-preact#37]
When I run "npm install --save next next-plugin-preact preact react@npm:@preact/compat react-dom@npm:@preact/compat react-ssr-prepass@npm:preact-ssr-prepass preact-render-to-string", I get a dependency conflict error.
<img width="1120" alt="Screen Shot 2021-08-03 at 04 04 18" src="https://user-images.githubusercontent.com/38510646/127956354-0690004f-6aec-40ce-a92e-09ec5b8323d6.png">
<img width="1112" alt="Screen Shot 2021-08-03 at 04 04 31" src="https://user-images.githubusercontent.com/38510646/127956363-d8231d5f-23f4-4caa-84e0-60d580a78629.png">

**Comment by rschristian** [comment]
Are you using NPM 7? I believe you need to do `npm install .... --legacy-peer-deps`

**Comment by marvinhagemeister** [comment]
@rschristian Sound alike we need to add v11 to our peer dependency definition

**Comment by rschristian** [comment]
Yeah, I worded that poorly. "I believe you need to do ... to continue right now" is what I had meant.

**Comment by neneodonkor** [comment]
> Are you using NPM 7? I believe you need to do `npm install .... --legacy-peer-deps`

I am running NPM 7.20.3

**Comment by neneodonkor** [comment]
> Yeah, I worded that poorly. "I believe you need to do ... to continue right now" is what I had meant. 

Oh okay sir.

**Comment by marvinhagemeister** [comment]
Ah I found the source of the problem. Npm seems to include the version now too when resolving rewritten `peerDependencies`. Next depends on `react ^17.0.0` and the install command rewrites that to `npm:@preact/compat@0.0.4`. But because `0.0.4` doesn't match `17.0.0` npm throws.

**Comment by neneodonkor** [comment]
I guess problem solved. ☺️

**Comment by neneodonkor** [comment]
Anyway this is the first time I am reporting an issue.

**Comment by marvinhagemeister** [comment]
@neneodonkor Just published a new version of `@preact/compat`, which resolves the installation error. Thanks again for letting us now about the issue and filing a report 🙌

**Comment by neneodonkor** [comment]
Thanks. I will try it again.
