### ISSUE TITLE
next.js update to 12v - building crashed

### ISSUE THREAD

**Issue by Zhanadil1509** [preactjs/next-plugin-preact#60]
Error: Cannot find module 'react-dom/server.browser'
Require stack:
- /home/projects/nextjs-preact-webpack5-t2s3fm/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (https://nextjs-preact-webpack5-t2s3fm.w.staticblitz.com/blitz.1becece65fb9e6d89d27bbe87eedd4d64b37a3a4.js:6:217231)
    
    https://stackblitz.com/edit/nextjs-preact-webpack5-t2s3fm?file=package.json

**Comment by thevinter** [comment]
Can confirm this is happening to me as well

**Comment by amursky** [comment]
+1

**Comment by aleppos** [comment]
+1

**Comment by cheeplusplus** [comment]
This was caused by upstream and appears to have been fixed in https://github.com/vercel/next.js/pull/36749

**Comment by nurliman** [comment]
so what do we do now?

**Comment by cheeplusplus** [comment]
use an earlier version? or run canary until the next full version is released

**Comment by lfre** [comment]
This is fixed in the latest (17.1.1) [@preact/compat](https://www.npmjs.com/package/@preact/compat) for Next 12.1.6.
